import pyautogui as py
py.press("win")
py.write("chrome")
py.press("enter")
py.sleep(2)
py.write("senai americana")
py.press("enter")
py.sleep(2)
py.click(329,463,button="left")
py.sleep(2)
py.click(1346,776,button="left")
py.sleep(3)
py.click(234,498,button="left")
py.write("python")
py.press("enter")
py.vscroll(-300)
